#服务端口
server.port:
  8002
#服务名
spring.application.name:
  service-oss
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#环境设置：dev、test、prod
spring.profiles.active:
  dev
#阿里云 OSS
#不同的服务器，地址不同
aliyun.oss.file.endpoint:
  oss-cn-shanghai.aliyuncs.com
aliyun.oss.file.keyid:
  LTAI5tJyxde5CebpqPz3Pm49
aliyun.oss.file.keysecret:
  rwcSDTWqpRc475dFyqvAsOg0SBBExQ
#bucket可以在控制台创建，也可以使用java代码创建
aliyun.oss.file.bucketname:
  ccclovelmm

